-- Migration 0041: undo must retract the notifications it invalidates.
--
-- Found in live testing: pressing Next patient then Undo left the 'called'
-- notification in place. Repeating it produced three "You have been
-- called — please proceed" messages for a patient who was still waiting.
-- The queue state reversed correctly; the message did not.
--
-- This is not cosmetic. A patient reading "please proceed" may physically
-- get up and go to the consultation room. An undone call did not happen,
-- so a notification asserting that it did is false and must be removed.
--
-- Only notifications generated BY the undone action are removed, matched
-- on kind, entry and creation time. Earlier notifications for the same
-- entry are untouched — they describe events that really did occur.

create or replace function public.undo_next_patient(p_action_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  caller uuid := public.auth_profile_id();
  act    public.nurse_actions;
  cfg    public.clinic_settings;
  r      jsonb;
  window_s int;
  removed int := 0;
begin
  select * into act from public.nurse_actions
   where nurse_id = caller and action_id = p_action_id for update;
  if not found then raise exception 'Action not found'; end if;
  if act.undone_at is not null then raise exception 'Already undone'; end if;

  select cs.* into cfg from public.clinic_settings cs
  join public.profiles p on p.clinic_id = cs.clinic_id where p.id = caller;
  window_s := coalesce(cfg.undo_window_seconds, 60);

  if now() - act.created_at > make_interval(secs => window_s) then
    raise exception 'This action can no longer be undone';
  end if;

  if exists (select 1 from public.nurse_actions
              where nurse_id = caller and created_at > act.created_at) then
    raise exception 'A later action has occurred; this can no longer be undone';
  end if;

  r := act.result;

  if r->>'status' = 'called' then
    if exists (select 1 from public.consultations
                where id = (r->>'consultation_id')::uuid and ended_at is not null) then
      raise exception 'That consultation has already ended; this can no longer be undone';
    end if;

    delete from public.consultations where id = (r->>'consultation_id')::uuid;
    update public.queue_entries set status = 'waiting', called_at = null
     where id = (r->>'queue_entry_id')::uuid and status = 'in_progress';

    -- Retract the "you have been called" message. The call is being
    -- undone, so the statement is no longer true.
    delete from public.notifications
     where queue_entry_id = (r->>'queue_entry_id')::uuid
       and kind = 'called'
       and created_at >= act.created_at - interval '5 seconds';
    get diagnostics removed = row_count;
  end if;

  -- Reopen the consultation that was closed by the undone action.
  if r->>'ended_consultation_id' is not null then
    update public.consultations
       set ended_at = null, exclude_from_prediction = false, exclusion_reason = null
     where id = (r->>'ended_consultation_id')::uuid;
    update public.queue_entries set status = 'in_progress', completed_at = null
     where id = (select queue_entry_id from public.consultations
                  where id = (r->>'ended_consultation_id')::uuid);
  end if;

  update public.nurse_actions set undone_at = now() where id = act.id;

  return jsonb_build_object(
    'status','undone',
    'restored_token', r->>'ended_token',
    'notifications_retracted', removed);
end;
$$;

notify pgrst, 'reload schema';
